//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab53_LINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spartan
    {
        public int SpartanID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string University { get; set; }
        public string Course { get; set; }
        public Nullable<int> Mark { get; set; }
    }
}
