//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snap_Lab_20_sql_from_xml
{
    using System;
    using System.Collections.Generic;
    
    public partial class testTable
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}
