//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace snap_lab_4_sql_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpartansTable
    {
        public int ID { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string University { get; set; }
        public string Course { get; set; }
        public string Grade { get; set; }
    }
}
